
[general]

	[general.general]
		streamer_mode = false
		modcore_warning = false
		gui_scale = false
		network_messages = false

	[general.online_status]
		show_essential_indicator_on_tab = false
		show_essential_indicator_on_nametags = false

	[general.experience]
		alternate_character_customizer = true
		essential_full = false

	[general.friends]
		invite_friends = false

[privacy]

	[privacy.general]
		display_current_server = false
		friend_privacy_settings = 0

[notifications]

	[notifications.general]
		disable_all_notifications = false
		message_sound = false
		online_friend_alert = false
		message_notifications = false
		group_message_notifications = false

[quality_of_life]

	[quality_of_life.fullscreen]
		windowed_fullscreen = true

	[quality_of_life.zoom]
		smooth_zoom_animation = false
		toggle_to_zoom = false
		smooth_camera_when_zoomed = true

